// Package policygen renders ready-to-apply admission policies (Kyverno or
// OPA/Gatekeeper) for a jurisdiction straight from its ruleset, so enforcement
// and evidence come from one source. The policy bodies are the Helm chart's,
// captured verbatim (see the //go:embed templates, regenerated by `make
// gen-policies`); only the region allow-list and ruleset id are parameterized.
// A CI parity test asserts the generated policies reach the same shared
// fixture-violation count as the chart.
package policygen

import (
	_ "embed"
	"fmt"
	"strings"
	"text/template"
)

//go:embed kyverno.yaml.tmpl
var kyvernoTmpl string

//go:embed gatekeeper.yaml.tmpl
var gatekeeperTmpl string

// Engines lists the engines Generate supports.
var Engines = []string{"kyverno", "gatekeeper"}

// Generate renders the admission policies for one engine, pinned to regions and
// labelled with rulesetID. Delimiters are «» so the policies' own Kyverno {{ }}
// JMESPath and Gatekeeper Rego pass through untouched.
func Generate(engine, rulesetID string, regions []string) (string, error) {
	var tmplText string
	switch engine {
	case "kyverno":
		tmplText = kyvernoTmpl
	case "gatekeeper":
		tmplText = gatekeeperTmpl
	default:
		return "", fmt.Errorf("unknown engine %q (want kyverno|gatekeeper)", engine)
	}
	if len(regions) == 0 {
		return "", fmt.Errorf("ruleset %q has no regions to enforce", rulesetID)
	}
	fm := template.FuncMap{
		"regions": func(indent int) string {
			pad := strings.Repeat(" ", indent)
			var b strings.Builder
			for i, r := range regions {
				if i > 0 {
					b.WriteByte('\n')
				}
				b.WriteString(pad + "- " + r)
			}
			return b.String()
		},
	}
	t, err := template.New(engine).Delims("«", "»").Funcs(fm).Parse(tmplText)
	if err != nil {
		return "", err
	}
	var buf strings.Builder
	if err := t.Execute(&buf, map[string]string{"RulesetID": rulesetID}); err != nil {
		return "", err
	}
	return buf.String(), nil
}
