apiVersion: v1
kind: Pod
metadata:
  name: checkout-eu
  namespace: shop
spec:
  nodeSelector:
    topology.kubernetes.io/region: eu-central-1
  containers:
    - name: app
      image: nginx:1.27-alpine
