package report

import (
	"fmt"
	"sort"
	"strings"

	"github.com/RamazanKara/regionlock/internal/rules"
)

// DiffEntry identifies a single finding across two reports.
type DiffEntry struct {
	RuleID    string `json:"ruleId"`
	Kind      string `json:"kind"`
	Name      string `json:"name"`
	Namespace string `json:"namespace"`
	Message   string `json:"message"`
}

// Diff is the delta between a baseline and a current report.
type Diff struct {
	BaselineScore float64     `json:"baselineScore"`
	CurrentScore  float64     `json:"currentScore"`
	NewViolations []DiffEntry `json:"newViolations"`
	Resolved      []DiffEntry `json:"resolved"`
	StillFailing  int         `json:"stillFailing"`
	Regressed     bool        `json:"regressed"`
}

func failKey(f FindingOut) string {
	return strings.Join([]string{f.RuleID, f.Kind, f.Namespace, f.Name}, "|")
}

// Compare computes the delta from baseline to current.
func Compare(baseline, current Report) Diff {
	baseFail := map[string]FindingOut{}
	for _, f := range baseline.Findings {
		if f.Status == rules.Fail {
			baseFail[failKey(f)] = f
		}
	}
	curFail := map[string]FindingOut{}
	for _, f := range current.Findings {
		if f.Status == rules.Fail {
			curFail[failKey(f)] = f
		}
	}

	d := Diff{BaselineScore: baseline.Summary.Score, CurrentScore: current.Summary.Score}
	for k, f := range curFail {
		if _, ok := baseFail[k]; !ok {
			d.NewViolations = append(d.NewViolations, toEntry(f))
		} else {
			d.StillFailing++
		}
	}
	for k, f := range baseFail {
		if _, ok := curFail[k]; !ok {
			d.Resolved = append(d.Resolved, toEntry(f))
		}
	}
	sortEntries(d.NewViolations)
	sortEntries(d.Resolved)
	d.Regressed = len(d.NewViolations) > 0
	return d
}

func toEntry(f FindingOut) DiffEntry {
	return DiffEntry{RuleID: f.RuleID, Kind: f.Kind, Name: f.Name, Namespace: f.Namespace, Message: f.Message}
}

func sortEntries(e []DiffEntry) {
	sort.Slice(e, func(i, j int) bool {
		if e[i].RuleID != e[j].RuleID {
			return e[i].RuleID < e[j].RuleID
		}
		return e[i].Name < e[j].Name
	})
}

// Markdown renders the diff as a PR-comment-ready summary.
func (d Diff) Markdown() string {
	var b strings.Builder
	head := "### 🔒 Regionlock: data-residency check"
	if d.Regressed {
		head = "### 🔒 Regionlock: ❌ new data-residency violations"
	} else if len(d.Resolved) > 0 {
		head = "### 🔒 Regionlock: ✅ residency violations resolved"
	}
	fmt.Fprintf(&b, "%s\n\n", head)
	fmt.Fprintf(&b, "Compliance score: **%.0f%%** → **%.0f%%**", d.BaselineScore, d.CurrentScore)
	switch {
	case d.CurrentScore > d.BaselineScore:
		fmt.Fprintf(&b, " ⬆️\n\n")
	case d.CurrentScore < d.BaselineScore:
		fmt.Fprintf(&b, " ⬇️\n\n")
	default:
		fmt.Fprintf(&b, "\n\n")
	}

	if len(d.NewViolations) > 0 {
		fmt.Fprintf(&b, "**%d new violation(s) introduced by this change:**\n\n", len(d.NewViolations))
		for _, e := range d.NewViolations {
			fmt.Fprintf(&b, "- `%s` %s/%s (%s): %s\n", e.RuleID, e.Kind, e.Name, e.Namespace, e.Message)
		}
		fmt.Fprintln(&b)
	}
	if len(d.Resolved) > 0 {
		fmt.Fprintf(&b, "**%d violation(s) resolved:**\n\n", len(d.Resolved))
		for _, e := range d.Resolved {
			fmt.Fprintf(&b, "- `%s` %s/%s (%s)\n", e.RuleID, e.Kind, e.Name, e.Namespace)
		}
		fmt.Fprintln(&b)
	}
	if len(d.NewViolations) == 0 && len(d.Resolved) == 0 {
		fmt.Fprintf(&b, "No change in data-residency posture. Still failing: %d.\n", d.StillFailing)
	}
	fmt.Fprintf(&b, "\n<sub>Generated by [Regionlock](https://github.com/RamazanKara/regionlock).</sub>\n")
	return b.String()
}

// Console renders the diff for a terminal.
func (d Diff) Console() string {
	var b strings.Builder
	fmt.Fprintf(&b, "Regionlock diff: score %.0f%% -> %.0f%%\n", d.BaselineScore, d.CurrentScore)
	fmt.Fprintf(&b, "  new violations: %d\n  resolved: %d\n  still failing: %d\n",
		len(d.NewViolations), len(d.Resolved), d.StillFailing)
	for _, e := range d.NewViolations {
		fmt.Fprintf(&b, "  + %s %s/%s (%s): %s\n", e.RuleID, e.Kind, e.Name, e.Namespace, e.Message)
	}
	for _, e := range d.Resolved {
		fmt.Fprintf(&b, "  - %s %s/%s (%s)\n", e.RuleID, e.Kind, e.Name, e.Namespace)
	}
	return b.String()
}

// ParseJSON decodes a report previously emitted with `--format json`.
func ParseJSON(b []byte) (Report, error) {
	var r Report
	if err := jsonUnmarshal(b, &r); err != nil {
		return Report{}, fmt.Errorf("parsing report JSON: %w", err)
	}
	return r, nil
}
