package report

import (
	"bytes"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/RamazanKara/regionlock/internal/rules"
	"github.com/go-pdf/fpdf"
)

func jsonIndent(v any) ([]byte, error)    { return json.MarshalIndent(v, "", "  ") }
func jsonUnmarshal(b []byte, v any) error { return json.Unmarshal(b, v) }

// --- PDF ------------------------------------------------------------------

// PDF renders the evidence report as a print-ready A4 PDF (core fonts only, so
// no external assets are needed).
func (r Report) PDF() ([]byte, error) {
	pdf := fpdf.New("P", "mm", "A4", "")
	pdf.SetMargins(15, 15, 15)
	pdf.SetAutoPageBreak(true, 15)
	tr := pdf.UnicodeTranslatorFromDescriptor("") // cp1252
	san := func(s string) string { return tr(sanitize(s)) }
	pdf.AddPage()
	const pageW = 210.0 - 30.0 // A4 width minus margins

	// Title
	pdf.SetFont("Helvetica", "B", 20)
	pdf.SetTextColor(20, 30, 60)
	pdf.CellFormat(0, 10, "Regionlock Evidence Report", "", 1, "L", false, 0, "")
	pdf.SetFont("Helvetica", "", 10)
	pdf.SetTextColor(90, 100, 120)
	pdf.CellFormat(0, 6, san(fmt.Sprintf("%s  ·  ruleset %s@%s  ·  %s",
		r.Ruleset.Title, r.Ruleset.ID, r.Ruleset.Version, r.Ruleset.Jurisdiction)), "", 1, "L", false, 0, "")
	pdf.Ln(3)

	// Verdict banner
	verdict := "COMPLIANT"
	rr, gg, bb := 31, 191, 117
	if !r.Summary.Compliant {
		verdict = "NON-COMPLIANT"
		rr, gg, bb = 255, 93, 108
	}
	pdf.SetFillColor(rr, gg, bb)
	pdf.SetTextColor(255, 255, 255)
	pdf.SetFont("Helvetica", "B", 14)
	pdf.CellFormat(0, 12, san(fmt.Sprintf("  VERDICT: %s        compliance score %.0f%%        %d pass / %d fail / %d skip",
		verdict, r.Summary.Score, r.Summary.Pass, r.Summary.Fail, r.Summary.Skip)),
		"", 1, "L", true, 0, "")
	pdf.Ln(4)

	// Meta
	pdf.SetTextColor(40, 40, 40)
	kv := [][2]string{
		{"Source", r.Source},
		{"Generated", r.GeneratedAt},
		{"Resources", fmt.Sprintf("%d", r.Summary.Resources)},
		{"Ruleset updated", r.Ruleset.Updated},
	}
	for _, row := range kv {
		pdf.SetFont("Helvetica", "B", 10)
		pdf.CellFormat(40, 6, san(row[0]), "", 0, "L", false, 0, "")
		pdf.SetFont("Helvetica", "", 10)
		pdf.CellFormat(0, 6, san(row[1]), "", 1, "L", false, 0, "")
	}
	pdf.Ln(3)

	// Control summary table
	sectionHeader(pdf, san, "Control summary")
	headers := []string{"Control", "Sev", "Pass", "Fail", "Skip", "Evidences (articles)"}
	widths := []float64{45, 14, 12, 12, 12, pageW - 95}
	tableHeader(pdf, san, headers, widths)
	pdf.SetFont("Helvetica", "", 9)
	for _, rc := range r.RuleScores {
		fill := rc.Fail > 0
		if fill {
			pdf.SetFillColor(255, 235, 237)
		}
		cells := []string{rc.RuleID, rc.Severity,
			fmt.Sprintf("%d", rc.Pass), fmt.Sprintf("%d", rc.Fail), fmt.Sprintf("%d", rc.Skip),
			articleList(rc.Articles)}
		tableRow(pdf, san, cells, widths, fill)
	}
	pdf.Ln(4)

	// Failures
	if r.Summary.Fail > 0 {
		sectionHeader(pdf, san, "Failures")
		pdf.SetFont("Helvetica", "", 9)
		for _, f := range r.Findings {
			if f.Status != rules.Fail {
				continue
			}
			pdf.SetTextColor(200, 40, 60)
			pdf.SetFont("Helvetica", "B", 9)
			pdf.MultiCell(0, 5, san(fmt.Sprintf("[%s]  %s/%s  (%s)", f.RuleID, f.Kind, f.Name, f.Namespace)), "", "L", false)
			pdf.SetTextColor(40, 40, 40)
			pdf.SetFont("Helvetica", "", 9)
			pdf.MultiCell(0, 5, san(fmt.Sprintf("    %s   {%s}", f.Message, articleList(f.Articles))), "", "L", false)
			pdf.Ln(1)
		}
		pdf.Ln(2)
	}

	// Namespaces
	sectionHeader(pdf, san, "Namespaces")
	nsHeaders := []string{"Namespace", "Pass", "Fail", "Skip", "Score"}
	nsWidths := []float64{pageW - 96, 24, 24, 24, 24}
	tableHeader(pdf, san, nsHeaders, nsWidths)
	pdf.SetFont("Helvetica", "", 9)
	for _, ns := range r.Namespaces {
		tableRow(pdf, san, []string{ns.Namespace,
			fmt.Sprintf("%d", ns.Pass), fmt.Sprintf("%d", ns.Fail), fmt.Sprintf("%d", ns.Skip),
			fmt.Sprintf("%.0f%%", ns.Score)}, nsWidths, false)
	}
	pdf.Ln(5)

	// Integrity footer
	pdf.SetDrawColor(200, 200, 200)
	pdf.SetFont("Helvetica", "B", 9)
	pdf.CellFormat(0, 5, "Integrity", "", 1, "L", false, 0, "")
	pdf.SetFont("Helvetica", "", 8)
	pdf.MultiCell(0, 4, san(fmt.Sprintf("%s: %s", r.Integrity.Algorithm, r.Integrity.Digest)), "", "L", false)
	if r.Integrity.Signature != nil {
		pdf.MultiCell(0, 4, san(fmt.Sprintf("signature (%s): %s", r.Integrity.Signature.Algorithm, r.Integrity.Signature.Value)), "", "L", false)
		pdf.MultiCell(0, 4, san("public key: "+r.Integrity.Signature.PublicKey), "", "L", false)
	}
	pdf.Ln(2)
	pdf.SetTextColor(120, 120, 120)
	pdf.SetFont("Helvetica", "I", 8)
	pdf.MultiCell(0, 4, san(r.disclaimer()), "", "L", false)
	pdf.MultiCell(0, 4, san("Generated by Regionlock "+r.Version), "", "L", false)

	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func sectionHeader(pdf *fpdf.Fpdf, san func(string) string, title string) {
	pdf.SetFont("Helvetica", "B", 12)
	pdf.SetTextColor(20, 30, 60)
	pdf.CellFormat(0, 7, san(title), "", 1, "L", false, 0, "")
	pdf.SetTextColor(40, 40, 40)
}

func tableHeader(pdf *fpdf.Fpdf, san func(string) string, headers []string, widths []float64) {
	pdf.SetFont("Helvetica", "B", 9)
	pdf.SetFillColor(235, 238, 245)
	pdf.SetTextColor(60, 70, 90)
	for i, h := range headers {
		pdf.CellFormat(widths[i], 7, san(h), "1", 0, "L", true, 0, "")
	}
	pdf.Ln(-1)
	pdf.SetTextColor(40, 40, 40)
}

func tableRow(pdf *fpdf.Fpdf, san func(string) string, cells []string, widths []float64, fill bool) {
	for i, c := range cells {
		align := "L"
		if i > 0 && i < len(cells)-1 {
			align = "C"
		}
		pdf.CellFormat(widths[i], 6, san(truncate(c, 60)), "1", 0, align, fill, 0, "")
	}
	pdf.Ln(-1)
}

func truncate(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n-1] + "…"
}

// sanitize maps the few non-cp1252 glyphs used in text output to ASCII so the
// PDF core fonts render them cleanly.
func sanitize(s string) string {
	repl := strings.NewReplacer(
		"✓", "OK", "✗", "x", "✅", "", "❌", "", "•", "-", "→", "->",
	)
	return repl.Replace(s)
}

// --- SARIF ----------------------------------------------------------------

// SARIF renders failing findings as SARIF 2.1.0 for GitHub code scanning.
func (r Report) SARIF() ([]byte, error) {
	driver := sarifDriver{
		Name:           "regionlock",
		InformationURI: "https://github.com/RamazanKara/regionlock",
		Version:        r.Version,
	}
	seenRule := map[string]bool{}
	var results []sarifResult
	for _, f := range r.Findings {
		if f.Status != rules.Fail {
			continue
		}
		if !seenRule[f.RuleID] {
			seenRule[f.RuleID] = true
			driver.Rules = append(driver.Rules, sarifRule{
				ID:               f.RuleID,
				Name:             f.RuleName,
				ShortDescription: sarifText{Text: f.RuleName},
				HelpURI:          "https://github.com/RamazanKara/regionlock#what-each-control-evidences",
				Properties: sarifRuleProps{
					SecuritySeverity: severityScore(f.Severity),
					Tags:             []string{"regionlock", "data-residency", "compliance"},
				},
			})
		}
		results = append(results, sarifResult{
			RuleID:  f.RuleID,
			Level:   sarifLevel(f.Severity),
			Message: sarifText{Text: fmt.Sprintf("%s [%s]", f.Message, articleList(f.Articles))},
			Locations: []sarifLocation{{
				PhysicalLocation: sarifPhysical{
					ArtifactLocation: sarifArtifact{URI: sourceURI(f.Source)},
				},
			}},
		})
	}
	doc := sarifDoc{
		Schema:  "https://json.schemastore.org/sarif-2.1.0.json",
		Version: "2.1.0",
		Runs:    []sarifRun{{Tool: sarifTool{Driver: driver}, Results: results}},
	}
	return jsonIndent(doc)
}

func severityScore(sev string) string {
	switch sev {
	case "high":
		return "8.0"
	case "medium":
		return "5.0"
	default:
		return "3.0"
	}
}

func sarifLevel(sev string) string {
	if sev == "high" {
		return "error"
	}
	return "warning"
}

func sourceURI(source string) string {
	if source == "" {
		return "cluster"
	}
	// Strip the "#<doc-index>" traceability suffix for a clean file URI.
	if i := strings.LastIndex(source, "#"); i >= 0 {
		return source[:i]
	}
	return source
}

type sarifDoc struct {
	Schema  string     `json:"$schema"`
	Version string     `json:"version"`
	Runs    []sarifRun `json:"runs"`
}
type sarifRun struct {
	Tool    sarifTool     `json:"tool"`
	Results []sarifResult `json:"results"`
}
type sarifTool struct {
	Driver sarifDriver `json:"driver"`
}
type sarifDriver struct {
	Name           string      `json:"name"`
	InformationURI string      `json:"informationUri"`
	Version        string      `json:"version"`
	Rules          []sarifRule `json:"rules"`
}
type sarifRule struct {
	ID               string         `json:"id"`
	Name             string         `json:"name"`
	ShortDescription sarifText      `json:"shortDescription"`
	HelpURI          string         `json:"helpUri"`
	Properties       sarifRuleProps `json:"properties"`
}
type sarifRuleProps struct {
	SecuritySeverity string   `json:"security-severity"`
	Tags             []string `json:"tags"`
}
type sarifResult struct {
	RuleID    string          `json:"ruleId"`
	Level     string          `json:"level"`
	Message   sarifText       `json:"message"`
	Locations []sarifLocation `json:"locations"`
}
type sarifLocation struct {
	PhysicalLocation sarifPhysical `json:"physicalLocation"`
}
type sarifPhysical struct {
	ArtifactLocation sarifArtifact `json:"artifactLocation"`
}
type sarifArtifact struct {
	URI string `json:"uri"`
}
type sarifText struct {
	Text string `json:"text"`
}
